module PgEventstore
  module CLI
    module Commands
      class HelpCommand
        attr_reader options: PgEventstore::CLI::ParserOptions::BaseOptions

        def initialize: (PgEventstore::CLI::ParserOptions::BaseOptions options) -> void

        %a{rbs:test:skip} def call: -> Integer
      end
    end
  end
end
