module PgEventstore
  module CLI
    module Commands
      class StartSubscriptionsCommand
        KEEP_ALIVE_INTERVAL: Integer

        @running: bool
        @subscription_managers: Set[PgEventstore::SubscriptionsManager]

        def initialize: (PgEventstore::CLI::ParserOptions::BaseOptions options) -> void

        %a{rbs:test:skip} def call: -> Integer

        private

        def attach_callbacks: -> void

        def keep_process_alive: -> void

        def persist_pid: -> void

        def running_subscriptions?: -> bool

        def setup_killsig: -> void
      end
    end
  end
end
