module PgEventstore
  module RunnerRecoveryStrategies
    class ReportUnrecoverableError
      include RunnerRecoveryStrategy

      @failed_subscription_notifier: _FailedSubscriptionNotifier?
      @subscription: Subscription

      def initialize: (
          subscription: Subscription,
          failed_subscription_notifier: _FailedSubscriptionNotifier?
        )-> untyped
    end
  end
end
