module PgEventstore
  module QueryStrategy
    class Async
      include QueryStrategy

      @connection: Connection

      def initialize: (Connection connection) -> void

      private

      def cancel_and_drain: (PG::Connection connection) -> void

      def run: (Symbol method, *untyped exec_args) -> untyped
    end
  end
end
