module PgEventstore
  module SubscriptionRunnerCommands
    class Restore < PgEventstore::SubscriptionRunnerCommands::Base
      # _@param_ `subscription_runner`
      def exec_cmd: (PgEventstore::SubscriptionRunner subscription_runner) -> void
    end
  end
end
