module PgEventstore
  class Client
    # _@param_ `config`
    def initialize: (Config config) -> void

    def append_to_stream: (
        Stream stream,
        (Event | ::Array[Event]) events_or_event,
        ?options: ::Hash[untyped, untyped],
        ?middlewares: ::Array[Symbol]?
      ) -> (Event | ::Array[Event])

    def multiple: (?read_only: bool) { () -> untyped } -> untyped

    def read: (Stream stream, ?options: ::Hash[untyped, untyped], ?middlewares: ::Array[::Symbol]?) -> ::Array[Event]

    def read_grouped: (Stream stream, ?options: Hash[untyped, untyped], ?middlewares: ::Array[::Symbol]?) -> ::Array[Event]

    # Temporary skip RBS checks of this method. It doesn't play well with Enumerator under certain circumstances
    %a{rbs:test:skip} def read_paginated: (
        Stream stream, ?options: ::Hash[untyped, untyped], ?middlewares: ::Array[::Symbol]?
      ) -> ::Enumerator[Array[Event], void]

    def link_to: (
        Stream stream,
        (Event | ::Array[Event]) events_or_event,
        ?options: ::Hash[untyped, untyped],
        ?middlewares: ::Array[::Symbol]
      ) -> (Event | ::Array[Event])

    attr_accessor config: Config

    def read_streams: (?options: ::Hash[untyped, untyped]) -> Array[Stream]

    def read_streams_paginated: (?options: ::Hash[untyped, untyped]) -> ::Enumerator[Array[Stream], void]

    def stream_revision: (Stream stream) -> Integer

    private

    def event_deserializer: (Array[Middleware] middlewares) -> EventDeserializer

    def event_marker_queries: -> EventMarkerQueries

    def event_subscription_position_queries: -> EventSubscriptionPositionQueries

    def events_global_index_queries: -> EventsGlobalIndexQueries

    def event_queries: -> EventQueries

    def index_filtering_queries: -> IndexFilteringQueries

    def partition_queries: () -> PartitionQueries

    def streams_global_index_queries: -> StreamsGlobalIndexQueries

    def transaction_queries: () -> TransactionQueries

    def middlewares: (?::Array[::Symbol]? middlewares) -> ::Array[Middleware]

    def append_deserialize_middlewares: (::Array[Middleware] middlewares) -> ::Array[Middleware]

    def connection: () -> Connection
  end
end
