module PgEventstore
  class Connection
    @pool: ConnectionPool[PgConnection]?

    attr_accessor uri: String
    attr_accessor pool_size: Integer
    attr_accessor pool_timeout: Integer

    def initialize: (uri: String, ?pool_size: Integer, ?pool_timeout: Integer) -> void

    def establish_connection: -> void

    def shutdown: -> void

    def with: () { (PgConnection connection) -> untyped } -> untyped

    private

    def init_pool: () -> ConnectionPool[PgConnection]

    def pg_type_registry: () -> PG::BasicTypeRegistry
  end
end
