module PgEventstore
  class Error < StandardError
    def as_json: () -> ::Hash[untyped, untyped]

    def to_h: () -> ::Hash[untyped, untyped]
  end

  class StreamNotFoundError < Error
    # _@param_ `stream`
    def initialize: (Stream stream) -> void

    # Returns the value of attribute stream.
    attr_accessor stream: Stream
  end

  class SystemStreamError < Error
    # _@param_ `stream`
    def initialize: (Stream stream) -> void

    attr_accessor stream: Stream
  end

  class WrongExpectedRevisionError < Error

    attr_accessor stream: Stream
    attr_accessor revision: Integer
    attr_accessor expected_revision: (Integer | Symbol)
    attr_accessor verdict: Symbol

    def initialize: (revision: Integer, expected_revision: (Integer | Symbol), stream: Stream, verdict: Symbol) -> void

    private

    def user_friendly_message: () -> String

    def expected_stream_exists: () -> String

    def expected_no_stream: () -> String

    def current_no_stream: () -> String

    def unmatched_stream_revision: () -> String

    def stream_descr: () -> String
  end

  class WrongExpectedTypesRevisionError < Error
    class Verdict
      include Extensions::OptionsExtension
      include Extensions::OptionsDefaults

      attr_accessor verdict: Symbol
      attr_accessor event_type: String | Symbol
      attr_accessor current_revision: Integer
      attr_accessor expected_revision: Integer | Symbol
      attr_accessor expected_markers: Array[String]?
    end

    attr_accessor stream: Stream
    attr_accessor verdicts: Array[Verdict]

    def initialize: (stream: Stream, verdicts: Array[Verdict]) -> void

    private

    def event_descr: (Verdict verdict) -> String

    def event_is_absent: (Verdict verdict) -> String

    def event_is_present: (Verdict verdict) -> String

    def event_revision_does_not_match: (Verdict verdict) -> String

    def revision_descr: (Verdict verdict) -> String

    def stream_descr: -> String

    def user_friendly_message: -> String
  end

  class RecordNotFound < Error
    attr_accessor table_name: String
    attr_accessor id: untyped

    def initialize: (String table_name, untyped id) -> void

    def user_friendly_message: () -> String
  end

  class SubscriptionAlreadyLockedError < Error
    # _@param_ `set` — subscriptions set name
    #
    # _@param_ `name` — subscription's name
    #
    # _@param_ `lock_id`
    def initialize: (String set, String name, Integer lock_id) -> void

    def user_friendly_message: () -> String

    attr_accessor set: String

    attr_accessor name: String

    attr_accessor lock_id: Integer
  end

  class WrongLockIdError < Error
    # _@param_ `set` — subscriptions set name
    #
    # _@param_ `name` — subscription's name
    #
    # _@param_ `lock_id`
    def initialize: (String set, String name, Integer lock_id) -> void

    def user_friendly_message: () -> String

    attr_accessor set: String

    attr_accessor name: String

    attr_accessor lock_id: Integer
  end

  class NotPersistedEventError < Error
    # _@param_ `event`
    def initialize: (PgEventstore::Event event) -> void

    def user_friendly_message: () -> String

    attr_accessor event: PgEventstore::Event
  end

  class MissingPartitions < Error
    # _@param_ `stream`
    #
    # _@param_ `event_types`
    def initialize: (Stream stream, ::Array[String] event_types) -> void

    attr_accessor stream: Stream

    attr_accessor event_types: ::Array[String]
  end

  class TooManyRecordsToLockError < Error
    def initialize: (Stream stream, Integer number_of_records) -> void

    attr_accessor stream: Stream

    attr_accessor number_of_records: Integer

    def user_friendly_message: -> String
  end

  class WrappedException < Error
    def initialize: (StandardError original_exception, Hash[Symbol, untyped] extra) -> void

    attr_accessor original_exception: StandardError

    attr_accessor extra: Hash[Symbol, untyped]
  end

  class NotSupportedError < Error
  end
end
