module PgEventstore
  class EventDeserializer
    def initialize: (::Array[Middleware] middlewares, _EventClassResolver event_class_resolver) -> void

    def deserialize_many: (::Array[::Hash[untyped, untyped]] | Enumerator[Hash[untyped, untyped]] raw_events) -> ::Array[Event]

    def deserialize: (::Hash[untyped, untyped] attrs) -> Event

    def without_middlewares: () -> EventDeserializer

    attr_accessor middlewares: ::Array[Middleware]

    attr_accessor event_class_resolver: _EventClassResolver
  end
end
