module PgEventstore
  class Maintenance
    @config: Config

    attr_reader config: Config

    def initialize: (Config config) -> void

    def connection: () -> Connection

    def delete_event: (Event event, ?force: bool)-> bool

    def delete_stream: (Stream stream)-> bool

    def maintenance_queries: () -> MaintenanceQueries

    def transaction_queries: () -> TransactionQueries

    private

    def events_global_index_queries: -> EventsGlobalIndexQueries
  end
end
