module PgEventstore
  class MaintenanceQueries
    attr_reader connection: PgEventstore::Connection

    def initialize: (PgEventstore::Connection connection)-> untyped

    def delete_stream: (PgEventstore::Stream stream)-> Integer
  end
end
