module PgEventstore
  class PgConnection < PG::Connection
    PLACEHOLDER_RE: untyped

    def exec: (untyped sql) -> untyped

    def exec_params: (untyped sql, untyped params) -> untyped

    def compile: (String sql, Array[untyped] params) -> String

    private

    def log: (untyped sql, untyped params) -> untyped

    def encode_value: (untyped value) -> untyped

    def normalize_value: (untyped value) -> untyped
  end
end
