module PgEventstore
  class Queries
    include Extensions::OptionsExtension

    attr_accessor events: EventQueries?
    attr_accessor partitions: PartitionQueries?
    attr_accessor transactions: TransactionQueries?
    attr_accessor maintenance: MaintenanceQueries?
    attr_accessor events_global_index: EventsGlobalIndexQueries?
    attr_accessor streams_global_index: StreamsGlobalIndexQueries?
    attr_accessor event_subscription_positions: EventSubscriptionPositionQueries?
  end
end
