module PgEventstore
  class Stream
    KNOWN_SYSTEM_STREAMS: Array[String]
    NON_EXISTING_STREAM_REVISION: Integer

    def self.all_stream: () -> Stream

    def self.system_stream: (String) -> Stream

    attr_reader context: String
    attr_reader stream_name: String
    attr_reader stream_id: String
    attr_reader stream_revision: Integer?
    attr_reader starting_position: Integer?

    def initialize: (context: String, stream_name: String, stream_id: String, ?stream_revision: Integer?,
        ?starting_position: Integer?) -> void

    def all_stream?: () -> bool

    def system?: () -> bool

    def deconstruct: () -> ::Array[untyped]

    def deconstruct_keys: (::Array[Symbol]? keys) -> ::Hash[Symbol, String]

    def to_hash: () -> ::Hash[untyped, untyped]

    def hash: () -> Integer

    def eql?: (untyped another) -> bool

    def ==: (untyped other_stream) -> bool
  end
end
