module PgEventstore
  class EventQueries
    attr_accessor connection: Connection

    def initialize: (Connection connection) -> void

    def insert: (Stream stream, ::Array[Event] events) -> ::Array[Hash[String, untyped]]

    private

    def prepared_statements: (Stream stream, ::Array[Event] events) -> ::Array[(::Array[String] | ::Array[Object])]

    def links_resolver: () -> LinksResolver
  end
end
