module PgEventstore
  class EventsGlobalIndexQueries
    @query_strategy: QueryStrategy

    attr_reader connection: Connection

    def initialize: (Connection connection, QueryStrategy query_strategy) -> void

    def compute_chunks_repo: (Array[EventGlobalIndex] indexes, bool resolve_link_tos) -> Chunks::Repository

    def create_global_indexes: (Array[[Integer, Integer]] indexes) -> void

    def fetch_grouped_indexes_for_read_api: (QueryBuilders::Filters::Collection filters_collection,
        QueryBuilders::ReadCursor::StreamCursor cursor) -> Array[EventGlobalIndex]

    def fetch_indexes_for_read_api: (QueryBuilders::Filters::Collection filters_collection,
        QueryBuilders::ReadCursor::StreamCursor cursor) -> Array[EventGlobalIndex]

    def fetch_indexes_for_revision_validation: (QueryBuilders::Filters::Collection filters_collection,
        QueryBuilders::ReadCursor::StreamCursor cursor) -> Array[EventGlobalIndex]

    def fetch_indexes_for_subscriptions: (Hash[Integer, Hash[Symbol, untyped]] grouped_opts) ->
      Hash[Integer, Array[EventGlobalIndex]]

    def global_positions_from_db: (Array[Event] events) -> Array[Integer]

    def index_events: (Array[Hash[String, untyped]] raw_events, Array[Partition] affected_partitions,
        Integer stream_index_id) -> void

    def max_global_position: -> Integer?

    def resolve_indexes: (Array[EventGlobalIndex] indexes, direction: String | Symbol,
        resolve_link_tos: bool) -> Array[Hash[String, untyped]]

    private

    def deserialize: (PG::Result pg_result)-> Array[EventGlobalIndex]

    def expand_event_types: (QueryBuilders::Filters::Collection filters_collection) ->
      QueryBuilders::Filters::Collection

    def links_resolver: -> LinksResolver

    def partition_queries: -> PartitionQueries
  end
end
