module PgEventstore
  class LinksResolver
    @query_strategy: QueryStrategy

    attr_accessor connection: Connection

    def initialize: (Connection connection, QueryStrategy query_strategy) -> void

    def resolve: (::Array[::Hash[String, untyped]] raw_events) -> ::Array[::Hash[String, untyped]]

    def load_original_events: (::Hash[Integer, ::Array[::Hash[String, untyped]]] link_events) -> ::Array[::Hash[String, untyped]]

    def partition_queries: () -> PartitionQueries
  end
end
