module PgEventstore
  class LinksResolver
    # _@param_ `connection`
    def initialize: (Connection connection) -> void

    # _@param_ `raw_events`
    def resolve: (::Array[::Hash[String, untyped]] raw_events) -> ::Array[::Hash[String, untyped]]

    # _@param_ `link_events` — partition id to link events association
    #
    # _@return_ — original events
    def load_original_events: (::Hash[Integer, ::Array[::Hash[String, untyped]]] link_events) -> ::Array[::Hash[String, untyped]]

    def partition_queries: () -> PartitionQueries

    # Returns the value of attribute connection.
    attr_accessor connection: Connection
  end
end
