module PgEventstore
  class PartitionQueries
    attr_accessor connection: Connection

    def initialize: (Connection connection) -> void

    def create_context_partition: (Stream stream) -> ::Hash[untyped, untyped]

    def create_stream_name_partition: (Stream stream, String context_partition_name,
        Integer context_partition_id) -> ::Hash[untyped, untyped]

    def create_event_type_partition: (Stream stream, String event_type, String stream_name_partition_name,
        Integer context_partition_id, Integer stream_name_partition_id) -> ::Hash[untyped, untyped]

    def partition_required?: (Stream stream, String event_type) -> bool

    def create_partitions: (Stream stream, String event_type) -> void

    def context_partition: (Stream stream) -> ::Hash[untyped, untyped]?

    def partitions: (QueryBuilders::Filters::Collection filters_collection, ?scope: Symbol) -> Array[Partition]

    def stream_name_partition: (Stream stream) -> ::Hash[untyped, untyped]?

    def event_type_partition: (Stream stream, String event_type) -> ::Hash[untyped, untyped]?

    def partition_name_taken?: (String table_name) -> bool

    def find_by_ids: (::Array[Integer] ids) -> ::Array[::Hash[untyped, untyped]]

    def context_partition_name: (Stream stream) -> String

    def stream_name_partition_name: (Stream stream) -> String

    def event_type_partition_name: (Stream stream, String event_type) -> String

    private

    def deserialize: (Hash[untyped, untyped] attrs)-> Partition

    def set_partitions_scope: (QueryBuilders::PartitionsFiltering partitions_filter, Array[untyped] stream_filters,
        Array[untyped] event_filters, Symbol scope) -> SQLBuilder
  end
end
