module PgEventstore
  class TransactionQueries
    ISOLATION_LEVELS: ::Hash[Symbol, String]

    # _@param_ `connection`
    def initialize: (PgEventstore::Connection connection) -> void

    # _@param_ `level` — transaction isolation level
    def transaction: (?Symbol level) -> void

    # _@param_ `level` — PostgreSQL transaction isolation level
    #
    # _@param_ `pg_connection`
    def pg_transaction: (String level, PG::Connection pg_connection) -> void

    def partition_queries: () -> PgEventstore::PartitionQueries

    # Returns the value of attribute connection.
    attr_accessor connection: PgEventstore::Connection
  end
end
