module PgEventstore
  module CLI
    class BaseOptions
      class Metadata
        def to_parser_opts: -> Array[String]
      end

      def attach_parser_handlers: (::OptionParser parser) -> void

      def to_parser_opts: (Symbol option) -> Array[String]

      def option: (Symbol option) -> PgEventstore::Extensions::OptionsExtension::Option
    end
  end
end
