module PgEventstore
  module Extensions
    module CallbackHandlersExtension
      def self.included: (untyped klass) -> untyped

      module ClassMethods
        def setup_handler: (Symbol name, *untyped args) { (*untyped) -> untyped } -> untyped
      end
    end
  end
end
