module PgEventstore
  module Commands
    module EventModifiers
      class PrepareLinkEvent
        @serializer: EventSerializer

        attr_reader partition_queries: PartitionQueries

        attr_reader partitions: Hash[untyped, untyped]

        def initialize: (PartitionQueries partition_queries, EventSerializer serializer) -> void

        def call: (Event event) -> Event

        private

        def partition_id: (Event event) -> Integer
      end
    end
  end
end
