module PgEventstore
  module Commands
    module EventModifiers
      class PrepareRegularEvent
        @serializer: EventSerializer

        def initialize: (EventSerializer serializer) -> void

        def call: (Event event) -> Event
      end
    end
  end
end
