module PgEventstore
  class CommandsHandler
    extend Forwardable

    PULL_INTERVAL: Integer

    @basic_runner: BasicRunner
    @config_name: Symbol

    @runners: ::Array[SubscriptionRunner]
    @subscription_feeder: SubscriptionFeeder

    # _@param_ `config_name`
    #
    # _@param_ `subscription_feeder`
    #
    # _@param_ `runners`
    def initialize: (Symbol config_name, SubscriptionFeeder subscription_feeder, ::Array[SubscriptionRunner] runners) -> void

    def attach_runner_callbacks: () -> untyped
  end
end
