module PgEventstore
  module EventsProcessorConsumer
    module ClassMethods
      def create_consumer: (_SubscriptionHandler handler, EventDeserializer deserializer) -> EventsProcessorConsumer
    end

    def self.consumer_class: (bool in_batches) -> Class

    def call: (Callbacks callbacks, Chunks::Repository repository,
        MonitorMixin::ConditionVariable repository_cond) -> void

    def clear_unprocessed_events: -> void
  end
end
