module PgEventstore
  class EventSubscriptionPositionQueries
    ASSIGN_SUBSCRIPTION_POSITIONS_LOCK_ID: Integer
    MAX_INDEX_RECORDS_TO_UPDATE_SUBSCRIPTION_POSITION: Integer
    REINDEX_PERIOD: Integer
    UNPROCESSED_POSITIONS_INDEX_NAME: String
    UNPROCESSED_POSITIONS_INDEX_SIZE_THRESHOLD: Integer
    UNPROCESSED_POSITIONS_LOCK_EXPIRES_IN: Integer

    attr_reader connection: Connection

    def initialize: (Connection connection) -> void

    def create_unprocessed_positions: (Array[Hash[String, untyped]] raw_events) -> void

    def max_subscription_position: -> Integer?

    def reindex_unprocessed_positions: -> Time?

    def subscription_positions_from_db: (Array[Event] events) -> Hash[Integer, Integer?]

    def assign_subscription_position: -> Integer?

    private

    def index_size: (String index_name) -> Integer

    def transaction_queries: -> TransactionQueries
  end
end
