module PgEventstore
  class EventsSubscriptionPositionWorker
    @basic_runner: BasicRunner

    attr_reader config_name: Symbol

    def initialize: (Symbol config_name) -> void

    private

    def attach_runner_callbacks: -> void

    def config: -> Config

    def connection: -> Connection

    def subscription_service_queries: -> SubscriptionServiceQueries
  end
end
