module PgEventstore
  class EventsProcessor
    include Extensions::CallbacksExtension

    extend Forwardable

    @basic_runner: BasicRunner
    @consumer: EventsProcessorConsumer
    @events_repository: Chunks::Repository
    @repository_cond: MonitorMixin::ConditionVariable

    %a{rbs:test:skip} def initialize: (
        graceful_shutdown_timeout: Float | Integer,
        consumer: EventsProcessorConsumer,
        ?events_repository: Chunks::Repository,
        ?recovery_strategies: Array[RunnerRecoveryStrategy]
      ) -> void

    def checkpoint: (Integer global_position) -> void

    def feed: (Chunks::Chunk[EventGlobalIndex, Hash[String, untyped]] chunk) -> void

    def events_left_in_repo: () -> Integer

    def clear_events_repository: () -> void

    def process_event: (::Hash[untyped, untyped] raw_event) -> void

    def attach_runner_callbacks: () -> void
  end
end
