module PgEventstore
  class EventsProcessor
    include PgEventstore::Extensions::CallbacksExtension
    extend Forwardable

    %a{rbs:test:skip} def initialize: (
        _RawEventHandler handler,
        graceful_shutdown_timeout: Float | Integer,
        ?recovery_strategies: Array[RunnerRecoveryStrategy]
      ) -> void

    def feed: (::Array[::Hash[untyped, untyped]] raw_events) -> void

    def events_left_in_chunk: () -> Integer

    def clear_chunk: () -> void

    def process_event: (::Hash[untyped, untyped] raw_event) -> void

    def attach_runner_callbacks: () -> void
  end
end
