module PgEventstore
  class EventSubscriptionPositionQueries
    INDEXES_UPDATE_LOCK_ID: Integer
    MAX_INDEX_RECORDS_TO_UPDATE_SUBSCRIPTION_POSITION: Integer

    attr_reader connection: Connection

    def initialize: (Connection connection) -> void

    def create_unprocessed_positions: (Array[Hash[String, untyped]] raw_events) -> void

    def max_subscription_position: -> Integer?

    def subscription_positions_from_db: (Array[Event] events) -> Hash[Integer, Integer?]

    def assign_subscription_position: -> Integer?

    private

    def transaction_queries: -> TransactionQueries
  end
end
