module PgEventstore
  class SubscriptionsManager
    extend Forwardable

    @set_name: String
    @subscription_feeder: SubscriptionFeeder
    @subscriptions_lifecycle: SubscriptionsLifecycle
    @subscriptions_set_lifecycle: SubscriptionsSetLifecycle

    def self.callbacks: () -> Callbacks

    def initialize: (
        config: Config,
        set_name: String,
        ?max_retries: Integer?,
        ?retries_interval: Integer?,
        ?force_lock: bool
      ) -> void

    def config_name: () -> Symbol

    def subscribe: (
        String subscription_name,
        handler: _SubscriptionHandler,
        ?options: ::Hash[untyped, untyped],
        ?middlewares: ::Array[Symbol]?,
        ?pull_interval: Integer | Float,
        ?max_retries: Integer,
        ?retries_interval: Integer | Float,
        ?restart_terminator: _RestartTerminator?,
        ?failed_subscription_notifier: _FailedSubscriptionNotifier?,
        ?graceful_shutdown_timeout: Integer | Float,
        ?in_batches: bool,
      ) -> void

    def subscriptions: () -> ::Array[Subscription]

    def subscriptions_set: () -> SubscriptionsSet?

    def deserializer: (::Array[Symbol]? middlewares) -> EventDeserializer

    def select_middlewares: (?::Array[Symbol]? middlewares) -> ::Array[Middleware]

    def start!: () -> BasicRunner

    def start: () -> BasicRunner?

    attr_accessor config: Config

    private

    def connection: -> Connection

    def recovery_strategies: (
        Subscription subscription,
        _RestartTerminator? restart_terminator,
        _FailedSubscriptionNotifier? failed_subscription_notifier
      ) -> Array[RunnerRecoveryStrategy]

    def run_cli_callbacks: () { () -> untyped } -> untyped
  end
end
