module PgEventstore
  module SubscriptionFeedStrategy
    def add: (*SubscriptionRunner runners) -> Array[SubscriptionRunner]

    def any?: -> bool

    def feed: -> void

    def size: -> Integer
  end
end
