module PgEventstore
  class SubscriptionRunnersFeeder
    @config_name: Symbol
    @current_database_id: Integer

    # _@param_ `config_name`
    def initialize: (Symbol config_name) -> void

    # _@param_ `runners`
    def feed: (::Array[SubscriptionRunner] runners) -> void

    def connection: () -> Connection

    def subscription_queries: () -> SubscriptionQueries

    private

    def current_database_id: -> Integer

    def subscription_service_queries: -> SubscriptionServiceQueries
  end
end
