module PgEventstore
  class SubscriptionRunnersFeeder
    @config_name: Symbol

    def initialize: (Symbol config_name) -> void

    def feed: (::Array[SubscriptionRunner] runners) -> void

    private

    def connection: -> Connection

    def subscription_service_queries: -> SubscriptionServiceQueries
  end
end
