module PgEventstore
  class SubscriptionRunner
    extend Forwardable
    MAX_EVENTS_PER_CHUNK: Integer
    MIN_EVENTS_PER_CHUNK: Integer
    INITIAL_EVENTS_PER_CHUNK: Integer

    # Returns the value of attribute subscription.
    attr_reader subscription: Subscription

    def initialize: (
        stats: SubscriptionHandlerPerformance,
        events_processor: EventsProcessor,
        subscription: Subscription,
        position_evaluation: SubscriptionPositionEvaluation,
      ) -> void

    def next_chunk_query_opts: () -> ::Hash[untyped, untyped]

    def next_chunk_safe?: -> bool

    def time_to_feed?: () -> bool

    def next_chunk_global_position: () -> Integer

    def estimate_events_number: () -> Integer

    def attach_callbacks: () -> void
  end
end
