module PgEventstore
  class SubscriptionFeeder
    EVENTS_PULL_INTERVAL: Float

    extend Forwardable

    @basic_runner: BasicRunner
    @commands_handler: CommandsHandler
    @events_subscription_position_worker: EventsSubscriptionPositionWorker?
    @subscriptions_lifecycle: SubscriptionsLifecycle
    @subscriptions_set_lifecycle: SubscriptionsSetLifecycle

    attr_reader config_name: Symbol

    def initialize: (
        config_name: Symbol,
        subscriptions_set_lifecycle: SubscriptionsSetLifecycle,
        subscriptions_lifecycle: SubscriptionsLifecycle
      ) -> void

    def id: -> Integer?

    def start_all: -> void

    def stop_all: -> void

    def attach_runner_callbacks: -> void

    private

    def recovery_strategies: (
        Symbol config_name,
        SubscriptionsSetLifecycle subscriptions_set_lifecycle
      ) -> Array[RunnerRecoveryStrategy]

    def requires_subscription_position_assignment?: -> bool
  end
end
