module PgEventstore
  class SubscriptionsLifecycle
    HEARTBEAT_INTERVAL: Integer

    @config_name: Symbol

    @subscriptions_set_lifecycle: SubscriptionsSetLifecycle

    @subscriptions_pinged_at: Time

    @force_lock: bool

    attr_reader runners: Array[SubscriptionRunner]

    def initialize: (Symbol config_name, SubscriptionsSetLifecycle subscriptions_set_lifecycle, ?force_lock: bool)-> void

    def force_locked?: -> bool

    def lock_all: -> void

    def ping_subscriptions: -> void

    def subscriptions: -> Array[Subscription]
  end
end
