module PgEventstore
  module SubscriptionFeedStrategy[unchecked Runner]
    def add: (Runner runner, Hash[Symbol, untyped] query_options) -> void

    def any?: -> bool

    def feed: -> void

    def size: -> Integer
  end
end
