module PgEventstore
  class SubscriptionFeeder
    extend Forwardable

    def initialize: (
        config_name: Symbol,
        set_name: String,
        max_retries: Integer,
        retries_interval: Integer,
        force_lock: bool
      ) -> void

    def id: () -> Integer

    # _@param_ `runner`
    def add: (PgEventstore::SubscriptionRunner runner) -> PgEventstore::SubscriptionRunner

    def start_all: () -> void

    def stop_all: () -> void

    def read_only_subscriptions: () -> ::Array[PgEventstore::Subscription]

    def read_only_subscriptions_set: () -> PgEventstore::SubscriptionsSet?

    def attach_runner_callbacks: () -> void

    def assert_proper_state!: () -> void
  end
end
