module PgEventstore
  module Web
    module Paginator
      class EventsCollection < BaseCollection
        SQL_DIRECTIONS: ::Hash[String, Symbol]
        PER_PAGE: ::Hash[String, Integer]
        MAX_NUMBER_TO_COUNT: Integer

        def collection: () -> ::Array[Event]

        def next_page_starting_id: () -> Integer?

        def prev_page_starting_id: () -> Integer?

        def total_count: () -> Integer

        def event_global_position: (Event? event) -> Integer?

        def estimate_count: (SQLBuilder sql_builder) -> Integer

        def regular_count: (SQLBuilder sql_builder) -> Integer

        def global_position: (SQLBuilder sql_builder) -> Integer?
      end
    end
  end
end
