module PgEventstore
  class CommandsHandlerHandlers
    def self.process_feeder_commands: (Symbol config_name, SubscriptionFeeder subscription_feeder) -> void

    def self.process_runners_commands: (
        Symbol config_name, Array[SubscriptionRunner] runners,
        SubscriptionFeeder subscription_feeder
      ) -> void
  end
end
