module PgEventstore
  class EventsSubscriptionPositionWorkerHandlers
    def self.assign_subscription_position: (EventSubscriptionPositionQueries event_subscription_position_queries,
          Integer | Float update_interval) -> void
  end
end
