module PgEventstore
  class EventsProcessorHandlers
    def self.consume_events: (EventsProcessorConsumer consumer, Callbacks callbacks, SynchronizedArray raw_events,
        MonitorMixin::ConditionVariable raw_events_cond) -> void

    def self.after_runner_died: (Callbacks callbacks, StandardError error) -> void

    def self.before_runner_restored: (Callbacks callbacks) -> void

    def self.change_state: (Callbacks callbacks, String state) -> void
  end
end
