module PgEventstore
  class SubscriptionRunnerHandlers
    def self.checkpoint: (Subscription subscription, Integer global_position) -> void

    def self.track_exec_time: (
        SubscriptionHandlerPerformance stats, ^() -> void,
        Integer _current_position,
        Integer events_number
      ) -> void

    def self.update_subscription_stats: (
        Subscription subscription,
        SubscriptionHandlerPerformance stats,
        Integer current_position,
        Integer events_number
      ) -> void

    def self.update_subscription_error: (Subscription subscription, WrappedException error) -> void

    def self.update_subscription_chunk_stats: (Subscription subscription, Integer subscription_position) -> void

    def self.update_subscription_restarts: (Subscription subscription) -> void

    def self.update_subscription_state: (Subscription subscription, String state) -> void
  end
end
