module PgEventstore
  module Web
    module Metrics
      class Application
        def metrics_connection: -> PgEventstore::Connection

        def config_name: -> Symbol
      end
    end
  end
end
