module PgEventstore
  module Web
    module Metrics
      module Helpers
        def metrics_response: (Array[untyped] collector_classes) -> String

        def requested_sets: -> Array[String]
      end
    end
  end
end
