module PgEventstore
  module Web
    module Metrics
      module Routes
        COLLECTORS_BY_PATH: Hash[String, Array[untyped]]

        def self.define: (untyped app, ?prefix: String) -> void
      end
    end
  end
end
