module PgEventstore
  module Web
    module Metrics
      module Collectors
        class Base
          STATEMENT_TIMEOUT: Integer

          @connection: PgEventstore::Connection

          @sets: Array[String]

          attr_reader connection: PgEventstore::Connection

          attr_reader sets: Array[String]

          def initialize: (PgEventstore::Connection connection, ?sets: Array[String]) -> void

          def call: -> Array[PgEventstore::Web::Metrics::MetricFamily]

          private

          def rows: (String sql, ?Array[untyped] params) -> Array[Hash[String, untyped]]

          def sets_condition: -> String

          def sets_params: -> Array[String]

          def subscription_labels: (Hash[String, untyped] row) -> Hash[Symbol, untyped]
        end
      end
    end
  end
end
