module PgEventstore
  module Web
    module Metrics
      module Collectors
        class Base
          STATEMENT_TIMEOUT: Integer

          LIVENESS_WINDOW: Integer

          @connection: PgEventstore::Connection

          def initialize: (PgEventstore::Connection connection) -> void

          def call: -> Array[PgEventstore::Web::Metrics::MetricFamily]

          private

          def rows: (String sql) -> Array[Hash[String, untyped]]

          def liveness_condition: -> String

          def subscription_labels: (Hash[String, untyped] row) -> Hash[Symbol, untyped]
        end
      end
    end
  end
end
