module PgEventstore
  module Web
    module Metrics
      module Collectors
        class SubscriptionsHealth < Base
          def call: -> Array[PgEventstore::Web::Metrics::MetricFamily]

          private

          def subscription_rows: -> Array[Hash[String, untyped]]
        end
      end
    end
  end
end
