module PgEventstore
  module EventsProcessorConsumer
    class Single
      include EventsProcessorConsumer
      extend ClassMethods

      @handler: _RawEventHandler

      @last_unprocessed_event: Hash[String, untyped]?

      def initialize: (_RawEventHandler handler) -> void
    end
  end
end

