module PgEventstore
  module QueryBuilders
    module BasicFiltering
      SQL_DIRECTIONS: Hash[String | Symbol, String]

      def to_exec_params: -> [String, Array[untyped]]

      def to_sql_builder: -> SQLBuilder

      def to_table_name: -> String
    end
  end
end
