module PgEventstore
  module QueryBuilders
    # @!visibility private
    class EventsFiltering
      include BasicFiltering

      DEFAULT_LIMIT: Integer

      @sql_builder: SQLBuilder

      def initialize: -> void

      def add_stream_attrs: (context: String, stream_name: String) -> void

      def add_event_types: (::Array[String] event_types) -> void

      def add_limit: (Integer? limit) -> void

      def correct_stream_filter?: (::Hash[untyped, untyped] stream_attrs) -> bool

      private

      def comparison_operator: (Array[String] event_types) -> String
    end
  end
end
