module PgEventstore
  module QueryBuilders
    class EventsGlobalIndexFiltering
      include BasicFiltering

      DEFAULT_LIMIT: Integer
      PRIMARY_TABLE_NAME: String

      @sql_builder: SQLBuilder

      def self.default_filtering: (ReadCursor::StreamCursor cursor) -> EventsGlobalIndexFiltering

      def self.for_read_common: (
          Filters::FilterRow filter_row,
          ReadCursor::StreamCursor cursor
        )-> SQLBuilder

      def self.for_read_grouped: (
          Filters::FilterRow filter_row,
          ReadCursor::StreamCursor cursor
        )-> SQLBuilder

      def self.for_revision_validation_per_type: (
          Filters::FilterRow filter_row, 
          ReadCursor::StreamCursor cursor,
          Integer seq_num
        )-> SQLBuilder

      def initialize: -> void

      def add_filter_row: (Filters::FilterRow filter_row) -> void

      def add_global_position_direction: (String? | Symbol? direction) -> void

      def add_limit: (Integer? limit) -> void

      def add_stream_revision_direction: (String? | Symbol? direction) -> void

      def for_subscription: -> void

      def from_position: (Integer? position, String? | Symbol? direction) -> void

      def from_revision: (Integer? revision, String? | Symbol? direction) -> void

      def to_position: (Integer? position, String? | Symbol? direction) -> void

      def to_revision: (Integer? revision, String? | Symbol? direction) -> void

      private

      def self.add_direction_and_limit: (
          EventsGlobalIndexFiltering index_filtering,
          ReadCursor::StreamCursor cursor
        ) -> void

      def self.filtering_from_filter_row: (
          Filters::FilterRow filter_row,
          ReadCursor::StreamCursor cursor
        ) -> EventsGlobalIndexFiltering

      def direction_operator_from: (String? | Symbol? direction) -> String

      def direction_operator_to: (String? | Symbol? direction) -> String

      def event_type_comparison: -> Array[String]
    end
  end
end
