module PgEventstore
  module QueryBuilders
    class PartitionsFiltering < BasicFiltering
      TABLE_NAME: String

      def self.extract_event_types_filter: (Hash[untyped, untyped] options) -> Array[String]

      def self.extract_streams_filter: (Hash[untyped, untyped] options) -> Array[Hash[untyped, untyped]]

      def self.correct_stream_filter?: (::Hash[untyped, untyped] stream_attrs) -> bool

      def add_event_types: (::Array[String] event_types) -> SQLBuilder

      def add_stream_attrs: (?context: String?, ?stream_name: String?) -> SQLBuilder

      def with_event_types: -> SQLBuilder

      def with_stream_names: -> SQLBuilder

      def without_event_types: -> SQLBuilder

      def without_stream_names: -> SQLBuilder
    end
  end
end
