module PgEventstore
  module QueryBuilders
    class PartitionsFiltering
      include BasicFiltering

      TABLE_NAME: String

      @sql_builder: SQLBuilder

      def self.assemble_sql_builder: (Filters::Collection filters_collection,
          ?scope: Symbol) -> SQLBuilder

      def self.from_filter_row: (Filters::FilterRow filter_row,
          ?scope: Symbol) -> SQLBuilder

      def add_filter_row: (Filters::FilterRow filter_row) -> SQLBuilder

      def order_by_context: -> SQLBuilder

      def order_by_event_type: -> SQLBuilder

      def order_by_stream_name: -> SQLBuilder

      def with_event_types: -> SQLBuilder

      def with_stream_names: -> SQLBuilder

      def without_event_types: -> SQLBuilder

      def without_stream_names: -> SQLBuilder

      private

      def self.has_stream_name_filter?: (Filters::Collection filters_collection) -> bool

      def self.set_partitions_scope: (PartitionsFiltering partitions_filtering, bool has_stream_name_filters,
          bool has_event_type_filters, Symbol scope) -> untyped
    end
  end
end
