module PgEventstore
  extend Extensions::ActsAsConfigurable

  attr_accessor logger: untyped

  def self.maintenance: (?Symbol name) -> Maintenance

  def self.subscriptions_manager: (
      ?Symbol config_name,
      subscription_set: String,
      ?max_retries: Integer?,
      ?retries_interval: Integer?,
      ?force_lock: bool
    ) -> SubscriptionsManager

  def self.client: (?Symbol name) -> Client

  private

  def self.connection_options: (Config config) ->
    { uri: String, pool_size: Integer, pool_timeout: Integer }
end
