module PgEventstore
  module QueryBuilders
    module Filters
      class FilterRow < Struct[untyped]
        attr_accessor stream_filter: StreamFilter?
        attr_accessor event_type_filters: Array[EventTypeFilter]

        def ambiguous_event_type?: -> bool

        def collapsable_into_event_types_only?: -> bool

        def flatten: -> Array[FilterRow]
      end
    end
  end
end
