module PgEventstore
  module CLI
    class TryUnlockSubscriptionsSet
      attr_reader config_name: Symbol

      attr_reader subscriptions_set_id: Integer

      def initialize: (Symbol config_name, Integer subscriptions_set_id) -> void

      def try_unlock: -> void

      private

      def config: -> PgEventstore::Config

      def connection: -> PgEventstore::Connection

      def find_set!: -> PgEventstore::SubscriptionsSet

      def subscriptions_set_commands_queries: -> PgEventstore::SubscriptionsSetCommandQueries

      def subscriptions_set_queries: -> PgEventstore::SubscriptionsSetQueries

      def try_to_delete: -> bool

      def try_to_wait_for_shutdown: -> bool
    end
  end
end
