module PgEventstore
  module Web
    module Subscriptions
      class SetCollection
        # _@param_ `connection`
        def initialize: (PgEventstore::Connection connection) -> void

        def names: () -> ::Array[String]

        def subscription_queries: () -> PgEventstore::SubscriptionQueries

        def subscriptions_set_queries: () -> PgEventstore::SubscriptionsSetQueries

        attr_accessor connection: PgEventstore::Connection
      end
    end
  end
end
