module PgEventstore
  module Web
    module Subscriptions
      class SubscriptionsSet
        # _@param_ `connection`
        #
        # _@param_ `current_set`
        def initialize: (PgEventstore::Connection connection, String? current_set) -> void

        def subscriptions_set: () -> ::Array[PgEventstore::SubscriptionsSet]

        def subscriptions_set_queries: () -> PgEventstore::SubscriptionsSetQueries

        attr_accessor connection: PgEventstore::Connection
      end
    end
  end
end
