module PgEventstore
  module Web
    class Application
      COOKIES_CONFIG_KEY: String
      COOKIES_FLASH_MESSAGE_KEY: String
      DEFAULT_ADMIN_UI_CONFIG: Symbol

      EMPTY_STRING_SIGN: String

      LOGGING_ENVS: Array[Symbol]

      def asset_url: (String path) -> String

      def connection: -> PgEventstore::Connection

      def current_config: -> Symbol

      def current_config=: (untyped val) -> void

      def escape_empty_string: (String? string) -> String?

      def events_filter: -> Array[String]?

      def flash_message=: (({ message: String, kind: String }) val)-> String

      def h: (String text) -> String

      def paginated_json_response: (PgEventstore::Web::Paginator::BaseCollection collection) -> void

      def redirect_back_url: (fallback_url: String) -> String

      def resolve_config_by_name: (Symbol? config_name)-> Symbol

      def resolve_link_tos?: -> bool

      def streams_filter: -> Array[Hash[untyped, untyped]]?

      def system_stream: -> String?

      def unescape_empty_string: (String? string) -> String?
    end
  end
end
