module PgEventstore
  module Chunks
    module Chunk[unchecked ElemIn, unchecked ElemOut]
      def drained?: -> bool

      def last: -> ElemIn?

      def size: -> Integer

      def take: (Integer? size) -> Array[ElemOut]
    end
  end
end
