module PgEventstore
  class SubscriptionServiceQueries
    INDEXES_UPDATE_LOCK_ID: Integer
    MAX_INDEX_RECORDS_TO_UPDATE_SUBSCRIPTION_POSITION: Integer

    attr_reader connection: Connection

    def initialize: (Connection connection) -> void

    def assign_subscription_position: -> Integer?

    def max_subscription_position: -> Integer?

    private

    def transaction_queries: -> TransactionQueries
  end
end
