module PgEventstore
  class SubscriptionQueries
    @query_strategy: QueryStrategy

    attr_accessor connection: Connection

    def initialize: (Connection connection, QueryStrategy query_strategy) -> void

    def create_or_replace_view: (Integer id, Hash[untyped, untyped] options, Integer locked_by) -> void

    def find_or_create_by: (::Hash[untyped, untyped] attrs) -> ::Hash[Symbol, untyped]

    def find_by: (::Hash[untyped, untyped] attrs) -> ::Hash[Symbol, untyped]?

    def find_all: (::Hash[untyped, untyped] attrs) -> ::Array[::Hash[Symbol, untyped]]

    def set_collection: (?String? state) -> ::Array[String]

    def find!: (Integer id) -> ::Hash[Symbol, untyped]

    def create: (::Hash[untyped, untyped] attrs) -> ::Hash[Symbol, untyped]

    def update: (Integer id, attrs: ::Hash[Symbol, untyped], locked_by: Integer?) -> ::Hash[Symbol, untyped]

    def ping_all: (Integer subscriptions_set_id, ::Array[Integer] subscriptions_ids) -> ::Hash[Integer, Time]

    def lock!: (Integer id, Integer lock_id, ?force: bool) -> Integer

    def delete: (Integer id) -> void

    def union_builders: (::Array[SQLBuilder] builders) -> SQLBuilder

    def transaction_queries: () -> TransactionQueries

    def links_resolver: () -> LinksResolver

    def deserialize: (::Hash[String, untyped] hash) -> ::Hash[Symbol, untyped]

    def find_by_attrs_builder: (::Hash[untyped, untyped] attrs) -> SQLBuilder
  end
end
