module PgEventstore
  module Commands
    class Append < AbstractCommand
      def call: (
          Stream stream,
          *Event events,
          event_modifier: _EventModifier,
          deserializer: EventDeserializer,
          ?options: ::Hash[untyped, untyped]
        ) -> ::Array[Event]

      private

      def feature_markers: (Event event) -> Array[String]

      def prepare_partitions: (Stream stream, ::Array[Event] events) -> Array[Partition]
    end
  end
end
