module PgEventstore
  module Commands
    class Append < AbstractCommand
      # _@param_ `stream`
      #
      # _@param_ `events`
      #
      # _@param_ `options`
      #
      # _@param_ `event_modifier`
      #
      # _@return_ — persisted events
      def call: (
          Stream stream,
          *Event events,
          ?options: ::Hash[untyped, untyped],
          ?event_modifier: _EventModifier
        ) -> ::Array[Event]

      # _@param_ `stream`
      #
      # _@param_ `events`
      def create_partitions: (Stream stream, ::Array[Event] events) -> Array[Partition]

      # _@param_ `revision`
      #
      # _@param_ `expected_revision`
      #
      # _@param_ `stream`
      def assert_expected_revision!: (Integer revision, (Symbol | Integer) expected_revision, Stream stream) -> void

      private

      def index_events: (Array[Event] events, Array[Partition] partitions) -> void
    end
  end
end
