module PgEventstore
  module Commands
    class LinkTo < AbstractCommand
      def call: (Stream stream, *Event events, event_modifier: _EventModifier, deserializer: EventDeserializer,
          ?options: ::Hash[untyped, untyped]) -> ::Array[Event]

      private

      def check_events_presence: (::Array[Event] events) -> void
    end
  end
end
