module PgEventstore
  module Commands
    class ReadGrouped < AbstractCommand
      def call: (Stream stream, deserializer: EventDeserializer, ?options: ::Hash[untyped, untyped]) -> Array[Event]
    end
  end
end
