module PgEventstore
  module Commands
    class ReadStreamsPaginated < AbstractCommand
      def call: (?options: ::Hash[untyped, untyped]) -> ::Enumerator[Array[Stream], void]

      private

      def calc_next_position: (StreamGlobalIndex indexes, String? | Symbol? direction) -> Integer

      def end_reached?: (Array[Stream] streams, Integer max_count) -> bool

      def forwards?: (String? | Symbol? direction) -> bool
    end
  end
end
