module PgEventstore
  module Commands
    class Read < PgEventstore::AbstractCommand
      # _@param_ `stream`
      #
      # _@param_ `options` — request options
      def call: (PgEventstore::Stream stream, ?options: ::Hash[untyped, untyped]) -> ::Array[PgEventstore::Event]
    end
  end
end
