module PgEventstore
  module Commands
    class SystemStreamReadPaginated < AbstractCommand
      %a{rbs:test:skip} def call: (Stream stream, deserializer: EventDeserializer,
          ?options: ::Hash[untyped, untyped]) -> ::Enumerator[Array[Event], void]

      private

      def end_reached?: (::Array[Event] events, Integer max_count) -> bool

      def calc_next_position: (::Array[Event] events, (String | Symbol)? direction) -> Integer

      # _@param_ `direction`
      def forwards?: ((String | Symbol)? direction) -> bool

      def read_cmd: () -> Commands::Read
    end
  end
end
