module PgEventstore
  module CommandHandlers
    class SubscriptionRunnersCommands
      # _@param_ `config_name`
      #
      # _@param_ `runners`
      #
      # _@param_ `subscriptions_set_id`
      def initialize: (Symbol config_name, ::Array[PgEventstore::SubscriptionRunner] runners, Integer subscriptions_set_id) -> void

      def process: () -> void

      def queries: () -> PgEventstore::SubscriptionCommandQueries

      def connection: () -> PgEventstore::Connection
    end
  end
end
