module PgEventstore
  module CommandHandlers
    class SubscriptionFeederCommands
      @config_name: Symbol

      @subscription_feeder: PgEventstore::SubscriptionFeeder

      # _@param_ `config_name`
      #
      # _@param_ `subscription_feeder`
      def initialize: (Symbol config_name, PgEventstore::SubscriptionFeeder subscription_feeder) -> void

      def process: () -> void

      def queries: () -> PgEventstore::SubscriptionsSetCommandQueries

      def connection: () -> PgEventstore::Connection

      private

      def commands: () -> Array[PgEventstore::SubscriptionFeederCommands::Base]
    end
  end
end
