module PgEventstore
  module SubscriptionFeedStrategy[unchecked Runner]
    class ReplicationStrategy
      include SubscriptionFeedStrategy[ReplicaSubscriptionRunner]

      @connection: Connection
      @query_strategy: QueryStrategy
      @runners_query_options: Hash[ReplicaSubscriptionRunner, Hash[Symbol, untyped]]

      def initialize: (Connection connection, QueryStrategy query_strategy) -> void

      private

      def events_global_index_queries: -> EventsGlobalIndexQueries
    end
  end
end
