name: Test & Publish

on:
  push:
    branches: [ release ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      if: ${{ !steps.skip-workflow.outputs.skip }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run PostgreSQL
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: docker compose up --detach
    - name: Install rbs collection
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: |
        bundle exec rbs collection install
    - name: Run tests
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: |
        sleep 10
        ./bin/setup_db
        ./bin/rspec
  push:
    needs: build
    name: Publish to RubyGems
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Publish
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
