name: Run tests

on:
  push:
    branches-ignore: [ release ]
  pull_request:
    branches: [ main release ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.169.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run PostgreSQL
        run: docker-compose up --detach
      - name: Run tests
        run: |
          sleep 10
          ./bin/setup_db
          TEST_COVERAGE=true bundle exec rspec
